### ISSUE TITLE
One oversight

### ISSUE THREAD

**Issue by trotsky1997** [BrendanGraham14/mcts-llm#1]
Thanks you for your work!
But please note. Every time a node is selected as an expansion object, it should be sampled again for self-reward, so that enough reward value samples can be obtained for approximation.

**Comment by BrendanGraham14** [comment]
Thanks for the comment, and good catch! Should be fixed by https://github.com/BrendanGraham14/mcts-llm/commit/be004f8ce41fa9341f5e82869b7965e36d0cc07e
